### PR TITLE
legacy-config: fix bug when migrating config.json

### PR DESCRIPTION
**Pull request by imrehg**
Trying to copy with wrong syntax (to a directory, instead of a file),
which breaks update process.

Commit-type: patch
Signed-off-by: Gergely Imreh <imrehg@gmail.com>

### CODE REVIEW

**Comment by willnewton** [comment]
Needs a changelog entry? Otherwise looks good to me.

**Comment by imrehg** [comment]
Yeah, adding that, cheers! :)

**Comment by imrehg** [comment]
Tested with 1.0.0-pre / 0.0.14

**Comment by imrehg** [comment]
Yeah, because you wrote it :)

**Pull request merged**
